import "./globals.css";
import dbConnect from "@/db/config";
import { Inter } from "next/font/google";
// import { ChakraProvider } from "@chakra-ui/react";
import { Providers } from "./providers";

// core styles are required for all packages
import "@mantine/core/styles.css";

import { MantineProvider, ColorSchemeScript } from "@mantine/core";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  await dbConnect();

  return (
    <html lang="en">
      <head>
        <ColorSchemeScript />
      </head>

      <body className={inter.className}>
        {" "}
        <MantineProvider>{children}</MantineProvider>
      </body>
    </html>
  );
}
