import dbConnect from "@/db/config";
import { Inter } from "next/font/google";
import NavBar from "./dbComponents/Navbar";
import SideBar from "./dbComponents/SideBar";

const inter = Inter({ subsets: ["latin"] });

const sidebarStyle = {
  marginTop: "3%",
  width: "14%",
  padding: "10px",
  backgroundColor: "white",
  color: "red",
};

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  await dbConnect();

  return (
    <main>
      <div className={`${inter.className} flex flex-col h-full`}>
        <div className="w-full fixed left-0 text-red-600">
          <NavBar />
        </div>
        <div className="flex w-full h-full">
          <div style={sidebarStyle}>
            <SideBar />
          </div>
          <div className="flex-initial w-full  pt-[90px] pl-[50px]">
            {children}
          </div>
        </div>
      </div>
    </main>
  );
}
