import dbConnect from "@/db/config";
import { Inter } from "next/font/google";
import Navbar from "./dbComponents/Navbar";
import NavBar from "./dbComponents/Navbar";
import SideBar from "./dbComponents/SideBar";

const inter = Inter({ subsets: ["latin"] });

const layoutStyle = {
  display: "flex",
  flexDirection: "column",
  height: "100vh",
};

const navbarStyle = {
  // height: "10%",
  width: "100%",
  backgroundColor: "red",
  color: "red",
  position: "fixed",
  left: "0",
};

const contentContainerStyle = {
  display: "flex",
  height: "100%",
  width: "100%",
};

const sidebarStyle = {
  marginTop: "3%",
  width: "14%",
  padding: "10px",
  backgroundColor: "white",
  color: "red",
};

const mainStyle = {
  flex: "1",
  backgroundColor: "#E5E7EB",
  padding: "200px", // Adjust as needed
};

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  await dbConnect();

  return (
    <html lang="en">
      <body className={inter.className} style={layoutStyle}>
        <div style={navbarStyle}>
          <NavBar />
        </div>
        <div style={contentContainerStyle}>
          <div style={sidebarStyle}>
            <SideBar />
          </div>
          <div style={mainStyle}>{children}</div>
        </div>
      </body>
    </html>
  );
}
