import dbConnect from "@/db/config";
import { Inter } from "next/font/google";
import { CollapsibleSideBar } from "../components/CollapsibleSidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  await dbConnect();

  return (
    <main>
      <div
        // className={gridStyles}
        // className="grid grid-cols-2"
        className={`${inter.className} flex flex-row`}
      >
        <div className="bg-white">
          <CollapsibleSideBar />
        </div>

        <div className=" flex flex-col w-full h-full m-0">
          <div
          // className={navbarStyle}
          // className="w-5/6 absolute top-0 right-0 m-0"
          >
            {/* <NavBar /> */}
          </div>

          <div className="flex-initial w-full  pt-[90px] pl-[50px]">
            {children}
          </div>
        </div>
        {/* */}
      </div>
    </main>
  );
}
